### ISSUE TITLE
Layer composer brainstorming

### ISSUE THREAD

**Issue by j8seangel** [GlobalFishingWatch/frontend#11]
Coming from [map-components/issues/64](https://github.com/GlobalFishingWatch/map-components/issues/64) this issue resume the main points of that conversation and opens the conversation in this repo.

Brainstorm 23/01/2020:

- [ ] Tests all existing generators - mapbox gl style check for each of them as a minimum
- [ ] Playground to test layers, we could even include a layer template for each type
- [ ] Generators need documentation
  - [x] Typescript already provides the first level of documentation 
  - [ ] Describe better methods using https://github.com/Microsoft/tsdoc
- [ ] Error handling: generators should throw when bad inputs are given
- [ ] We need a **core generator class** that generators extend:
    - [x] Manage standard style behaviours : visibility, interactive, selected/highlighted states with default and overrides system
    - [ ] Common utilities set: color handling/conversion
    - [ ] ~Handle overrides~ done by dataviews-client
    - [x] Pass global parameters : start/end. others?

- [ ] **InteractionManager** as done in the Books project:
  - [ ] Based on LayerManager input parameters
  - [ ] Responsible for generation of `interactiveLayerIds`
  - [ ] Handles feature interaction priority
  - [ ] Prepares popup data in a standard way
  - [ ] Overwrites style generated by LM depending on `selectedFeatures` and `highlightedFeatures` for each layer?
  - [ ] Manages map cursor states?
  - [ ] Handles cluster interactivity? (ie zoom to zoom level X when feature is clustered, do whatever when feature is not clustered)
  - [ ] selectedFeatures: support multiple features and expressions (might be overkill for now)

- [ ] **LegendManager** / **Legend component**
  - [ ] Reads standardised legend data generated by LayerManager in map style

- [ ] Attributions / AttributionManager

**map-styler**
- `compose` (params -> GL style)
- `sort` (GL style -> GL style)
- `getFeatures` (GL style -> GL style with selected features, selected features info, `interactiveLayerIds`)
- `getAttributions` (GL style -> attributions)
- `getLegends` (GL style -> legends)

**Comment by nerik** [comment]
Largely outdated, see https://github.com/GlobalFishingWatch/frontend/tree/develop/packages/layer-composer

![cool-story-bro](https://user-images.githubusercontent.com/1583415/124745864-8d72f180-df20-11eb-9720-32750d1bb5a2.jpg)
